Vagrant.configure(2) do |config|
   config.vm.define "testVm" do |testVm|
      testVm.vm.box = "centos/7"
      testVm.vm.hostname = "testvm"
      testVm.vm.network :private_network, ip: "192.168.33.32"
      testVm.vm.provision "ansible" do |ansible|
        ansible.playbook = "src/main/ansible/vagrant.yml"
      end
      testVm.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = 2072
        vb.cpus = 2
        vb.customize ["guestproperty", "set", :id, "--timesync-threshold", "1000"]
        vb.customize ["guestproperty", "set", :id, "--timesync-interval", "1000"]
      end
   end
end
